<?php

namespace app\controllers;

use app\models\PhoneForm;
use app\models\User;
use app\modules\catalogHeight\models\Product;
use Yii;
use yii\filters\AccessControl;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\ContactForm;

class SiteController extends ShopController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action)
    {
        $this->setMetaTags();

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $products = Product::find()->active()->all();

        return $this->render('index', ['products' => $products]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new PhoneForm();

        if ($model->load(Yii::$app->request->post())) {
            if ($model->phone && !$model->verificationCode) {
                $user = $model->getUser();

                if (!$user) {
                    $user = new User([
                        'username'      => $model->username ?? '',
                        'phone'         => $model->phone,
                        'email'         => "{$model->phone}@mail.ru",
                        'status'        => User::STATUS_ACTIVE,
                        'auth_key'      => 'empty',
                        'password_hash' => 'empty',
                    ]);

                    $user->save();
                }

                if ($user->checkVerificationCode()) {
                    \Yii::$app->session->setFlash(
                        'success',
                        "На указанный Вами номер уже сделан звонок. Код действителен 5 минут."
                    );
                } else {
                    $user->setVerificationCode();

                    \Yii::$app->session->setFlash(
                        'success',
                        "На указанный Вами номер сейчас позвонят. Сбросьте вызов и введите в поле \"код\" последние 4 цифры. Код действителен 5 минут."
                    );
                }

                $model->withCode = true;

                return $this->render('login', [
                    'model' => $model,
                ]);
            }

        }

        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();

        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }

        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }


    public function actionError()
    {
        $exception = Yii::$app->errorHandler->exception;

        if ($exception) {
            return $this->render('error', ['name' => '', 'exception' => $exception]);
        }
    }
}
