<?php

namespace app\modules\control\models;

use app\modules\control\interfaces\PathInterface;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

class MathematicsRecord extends \yii\db\ActiveRecord implements PathInterface
{
    protected $uploadDocumentRoot;
    public $picture;

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
            [
                'class' => BlameableBehavior::className(),
                'createdByAttribute' => 'created_user',
                'updatedByAttribute' => 'updated_user',
            ],
        ];
    }

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->setUploadDocumentRoot();
    }

    protected function setUploadDocumentRoot(){
        $this->uploadDocumentRoot = $_SERVER['DOCUMENT_ROOT'];
    }

    // path interface methods
    public function getBasePath(){
        return '';
    }

    public function getUploadDocumentRoot(){
        return $this->uploadDocumentRoot;
    }

    public function getOriginalFolder(){
        return '/original';
    }

    public function getBigFolder(){
        return '/big';
    }

    public function getSmallFolder(){
        return '/small';
    }

    public function getBigPath(){
        if(file_exists($this->uploadDocumentRoot . str_replace($this->originalFolder,$this->bigFolder,$this->image))){
            return str_replace($this->originalFolder,$this->bigFolder,$this->image);
        }
        return false;
    }

    public function getSmallPath(){
        if(file_exists($this->uploadDocumentRoot . str_replace($this->originalFolder,$this->smallFolder,$this->image))){
            return str_replace($this->originalFolder,$this->smallFolder,$this->image);
        }
        return false;
    }
}
